# Setting up data using headwaters package
# Shenandoah

### Load headwaters package
```{r}
load_all(pkg = "C:/ALR/Models/headwaters")
```

### Shenandoah files
```{r}
model.dir<-"C:/ALR/Models/headwaters_sdoah"
buffer.file<-"park_coast_buffer"
buffer<-readShapePoly(file.path(model.dir,"sdoah_inputs",buffer.file))
catchment.file<-"C:/ALR/Data/StreamData/NHDplus/NHDPlusCatchment/sdoah/Catchment"
```

### Load flow gages
```{r}
g.spatial<-gage.retrieve(buffer.file = file.path(model.dir,"sdoah_inputs",buffer.file),temp.dir = file.path(model.dir,"temp"),log.dir = file.path(model.dir,"logs") )

plot(g.spatial,col="blue",pch=16)
plot(buffer,add=T,border="red")
plot(states.spatial,add=T)

g.spatial<-gage.plot.nhdplus(gages.spatial = g.spatial, catchment.file = catchment.file)
# g.spatial<-gage.plot.nhdplus(gages.spatial = g.spatial, catchments=catchments)
# bkup1<-g.spatial
# g.spatial<-bkup1

# class(g.spatial)
g.spatial<-gage.trace.dams(gages.spatial = g.spatial)
# g.spatial<-gage.trace.dams(gages.spatial = g.spatial[1:20,])

nrow(g.spatial)
g.spatial<-gage.filter.dams(gages.spatial = g.spatial)
nrow(g.spatial)

g.spatial<-gage.load.char(gages.spatial = g.spatial, basin.char.file = file.path(model.dir,"sdoah_inputs","shenandoahUpstreamStats2.RData"))
# bkup2<-g.spatial

# class(g.spatial)
# str(g.spatial@data)
# 
# rm(catchments, plusflow)
# gc(verbose = T)
# ls.objects()
```


### Load flow observations
```{r}
# q.matrices<-flow.retrieve(gages.spatial = g.spatial, periods = c("seasonal","annual"), log.dir = file.path(model.dir,"logs") )
     
# q.bkup<-q.matrices
# q.matrices<-q.bkup

# bkup.g.spatial<-g.spatial
g.spatial<-g.spatial[!is.na(g.spatial$forest),]

q.matrices<-flow.retrieve( gages.spatial = g.spatial, 
                          periods = c("seasonal","annual"), log.dir = file.path(model.dir,"logs") )

```


### Load weather observations
```{r}
# weather.grid.poly <- weather.grid.create( regions=c("east","ohio") )
# 
# bkup3<-g.spatial

g.spatial<-gage.plot.weather( gages.spatial=g.spatial[!is.na(g.spatial$forest),], plot=T )

w.matrices <- weather.retrieve(gages.spatial=g.spatial, periods=c("seasonal","annual"))







# gages.spatial, 
#                            periods=c("seasonal","annual"),
#                            create.cols.function = create.cols.weather,
#                            agg.function = agg.function.weather,
#                            weather.dir="C:/ALR/Data/ClimateData/Mauer/daily/east",
#                            log.dir=NULL
# tail(g.spatial@data)

```

### Merge gage (basin char and drainage area), flow, and weather
```{r}

```



###Junk
```{r}
setwd("C:/ALR/Models/headwaters_sdoah/temp")
writeOGR(g.spatial,  ".", layer="sdoah_gages", driver="ESRI Shapefile")
names(g.spatial)

sum(duplicated(UpstreamStats$FEATUREID))
length(UpstreamStats$FEATUREID)
length(unique(UpstreamStats$FEATUREID))
UpstreamStats<-UpstreamStats[!duplicated(UpstreamStats$FEATUREID),]
save(UpstreamStats, file=file.path(model.dir,"sdoah_inputs","shenandoahUpstreamStats2.RData"))


nrow(boo)


View(boo)
nrow(boo)
boo2<-merge(catchments,boo,by="FEATUREID")
boo2<-boo2[!is.na(boo2@data$forest),]
plot(boo2,col="orange")
str(boo)
View(UpstreamStats)


```


